import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  base: process.env.NODE_ENV === 'production' ? '/nyhl-game-centre/' : '/',
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // Registration lives in src/lib/pwa.js instead of the injected
      // registerSW.js: it passes updateViaCache 'none' (GitHub Pages caches
      // sw.js for 10 minutes), nudges an update when a long-lived mobile tab
      // comes back to the foreground, and reloads once when a new worker
      // takes over. The injected script only called register(), so a phone
      // kept running the old bundle until the user refreshed repeatedly.
      injectRegister: null,
      // Not favicon.png only — see globIgnores: the data JSONs used to be
      // precached too, which hid every redeploy's fresh standings.
      includeAssets: ['favicon.png'],
      manifest: {
        name: 'North York Hockey League Game Center',
        short_name: 'NYHL',
        description: 'Schedules, standings, and results for your NYHL teams',
        theme_color: '#1e3a5f',
        background_color: '#ffffff',
        display: 'standalone',
        start_url: '/nyhl-game-centre/',
        // Generated by scripts/make-icons.js from the puck-and-stick art in
        // scripts/assets (see that folder's icon-template.html).
        // onto the theme colour. Without these the install prompt has nothing
        // to show and the console reports a manifest fetch error.
        icons: [
          {
            src: '/nyhl-game-centre/icon-192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: '/nyhl-game-centre/icon-512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: '/nyhl-game-centre/icon-180.png',
            sizes: '180x180',
            type: 'image/png',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,json}'],
        // The data JSONs must NOT be precached: precache is cache-first and
        // its route matches before the runtime route below, so the copy from
        // the last deploy would answer every request — fresh standings stayed
        // invisible until a service worker update landed (and on mobile that
        // update could take days). They go through NetworkFirst instead:
        // current when online (a conditional request, which also beats GitHub
        // Pages' own 10-minute HTTP cache), the last copy when offline.
        globIgnores: ['**/data/*.json'],
        runtimeCaching: [
          {
            urlPattern: /^\/nyhl-game-centre\/data\/.*\.json$/,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'nyhl-data',
              networkTimeoutSeconds: 5,
              fetchOptions: { cache: 'no-cache' },
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24, // 24 hours
              },
            },
          },
        ],
      },
    }),
  ],
  build: {
    outDir: 'dist',
    sourcemap: false,
  },
})
